# Generated by Django 5.0.1 on 2024-01-29 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0003_task_is_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_text',
            field=models.TextField(blank=True, max_length=100, verbose_name='Aprašymas'),
        ),
    ]
